### ISSUE TITLE
Is there a way to scale up ResultsRoot Panel and its content

### ISSUE THREAD

**Issue by arif6633** [m-wilczynski/UnityUIComponents#1]
Is there a way to scale up ResultsRoot Panel and its content: 
This is the current size which has a scale of 0.5
![screen shot 2017-09-01 at 16 23 30](https://user-images.githubusercontent.com/20264461/29966998-0854ed56-8f32-11e7-9d62-bef4e2e9d6e8.png)

When I scale it to 1.0 its looking readable and good for mobile but this settings cannot be saved.

![screen shot 2017-09-01 at 16 24 50](https://user-images.githubusercontent.com/20264461/29967045-4510645a-8f32-11e7-86c4-a5a99a82062e.png)
I love this and if this could be done this will great.
Thanks

**Comment by m-wilczynski** [comment]
I will take a look and come back to you today.  🔬

**Comment by m-wilczynski** [comment]
@arif6633 
I've checked behaviour you are mentioning and for me, example **TestScene** from https://github.com/m-wilczynski/UnityUIComponents/tree/master/examples/Localwire.UnityUIComponents.Examples/Assets does not ever scale to 0.5 (it stays on Play and afterwards as 1.0 scale in all dimensions).

Could you perhaps provide an example scene with behavior you are describing, so I could troubleshoot?
Thanks!

**Comment by arif6633** [comment]
@m-wilczynski 
I have attached a screenshot. I have put the input field width to 435, but the autocomplete part is not matching the size, you can see from the screenshot that the font is quite small. Anyway to make it bigger would be great. Also, the search is case-sensitive; if you can make it no case-sensitive this would be nice.
![screen shot 2017-09-09 at 10 56 16](https://user-images.githubusercontent.com/20264461/30237366-02053eca-954e-11e7-8350-e0d48cdd77ea.png)

**Comment by m-wilczynski** [comment]
Where do you change the width of input field?
You should've done so on **Autocomplete** component:

![image](https://user-images.githubusercontent.com/6330789/30290664-7952bb90-9730-11e7-86dc-9229195ba33c.png)


If you want your search to be case-sensitive, you can for example always compare input and source as both `ToUpper()`.
Example based on **JsonLocationsSource**:

```
        public IEnumerable<Location> Find(string searchString)
        {
            LoadIfNeeded();
            return _locations.Where(loc => loc.City.ToUpper().Contains(searchString.ToUpper()));
        }
```
